### ISSUE TITLE
Question: Ability to check all folders except root?

### ISSUE THREAD

**Issue by gav-fyi** [lk16/detect-missing-init#6]
Hi,

I came across this package that works great on my Django project. However, I have one small niggle that I don't seem to be able to resolve with the current available settings. 

I have a Django project that has many apps. I'd like to scan every app in the project, including any new apps that may get added.  I have been trying to use `--python-folders .` which works for all folders except the root. It tries to add an `__init__.py` file to the root of my project where I don't want one to exist. 

I have tried various paths with combinations of `.`, `/` and `*` with no luck. 

I'm not sure if there is a path I can use to target _only_ subdirectories, or whether this is just a limitation of the library/my project.

Thanks.

**Comment by lk16** [comment]
Hi,

This behaviour is currently not supported directly by this project.
However I found a way to achieve it by using subcommands:

```yaml
repos:
  - repo: https://github.com/lk16/detect-missing-init
    rev: v0.1.6
    hooks:
      - id: detect-missing-init
        entry: bash -c 'detect-missing-init --create --track --python-folders $(ls -d */ | sed "s:/$::" | paste -sd,)'
```

This config was tested on a dummy project and does what you want.

I hope this helps!
Sorry for the late response and thanks for using my project.

lk16
